development:
  adapter: postgresql
  encoding: unicode
  database: <%= File.basename(Rails.root) %>_development
  pool: 5
  host: localhost


test:
  adapter: postgresql
  encoding: unicode
  database: <%= File.basename(Rails.root) %>_test
  pool: 5
  host: localhost


production:
  adapter: postgresql
  encoding: unicode
  database: <%= File.basename(Rails.root) %>
  pool: 5
  host: localhost
