development:
  adapter: postgresql
  database: watchio_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: watchio_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: watchio
  pool: 5
  timeout: 5000
